### ISSUE TITLE
Is there a way to add Prism plugins?

### ISSUE THREAD

**Issue by sarunw** [11ty/eleventy-plugin-syntaxhighlight#58] opened 2021-08-02 16:29 UTC
I want to use https://prismjs.com/plugins/keep-markup/ but can't find a way to do this with eleventy-plugin-syntaxhighlight. Is this possible?

**Comment by boehs** [comment] 2022-04-03 02:18
duplicate of https://github.com/11ty/eleventy-plugin-syntaxhighlight/issues/4

**Comment by zachleat** [comment] 2022-06-28 19:18
Yeah #4 is the thing! Note that some prism.js plugins seem to require clientside operation 👀

**Closed by zachleat** 2022-06-28 19:18 UTC
Labels: duplicate
