### ISSUE TITLE
HTML entities are not encoded when using plain text

### ISSUE THREAD

**Issue by svivian** [11ty/eleventy-plugin-syntaxhighlight#36] opened 2020-10-08 16:28 UTC
Using this Markdown code:

    ```text
    <b>test</b>
    ```

The HTML is not encoded and I end up with a code block that just says "test", in bold. In other words this is the HTML output:

    <pre class="language-text"><code class="language-text"><b>test</b></code></pre>

It should be this:

    <pre class="language-text"><code class="language-text">&lt;b&gt;test&lt;/b&gt;</code></pre>
    
Using any other language (e.g. js) encodes the entities correctly. As does omitting a language (just using ```) but then you don't get the default highlighting (box colour etc).

**Comment by zachleat** [comment] 2022-06-28 19:36
Duplicate of https://github.com/11ty/eleventy-plugin-syntaxhighlight/issues/54#issuecomment-1169031169 (some discussion and solutions over there, thank you!)

**Closed by zachleat** 2022-06-28 19:36 UTC
Labels: duplicate
