### ISSUE TITLE
Inline code support

### ISSUE THREAD

**Issue by joepetrillo** [11ty/eleventy-plugin-syntaxhighlight#71] opened 2022-07-26 00:45 UTC
Hi, does anyone have a way for this plugin to work with inline code `like this`?

Thanks!

**Comment by zachleat** [comment] 2022-11-01 21:50
Duplicate of https://github.com/11ty/eleventy-plugin-syntaxhighlight/issues/38

**Closed by zachleat** 2022-11-01 21:51 UTC
